export const VehicleDetails = [
	{
		vehicleBrandID: 11,
		brand: "Toyota",
		logo: require("./assets/images/vehicles/Toyota/Toyota.png"),
		models: [
			{
				vehicleModelID: 111,
				model: "Avalon",
				MPG: 32,
				rating: 4,
				country: "Japan",
				image: require("./assets/images/vehicles/Toyota/111.png"),
			},
			{
				vehicleModelID: 112,
				model: "Camry",
				MPG: 32,
				rating: 4,
				country: "Japan",
				image: require("./assets/images/vehicles/Toyota/112.png"),
			},
			{
				vehicleModelID: 113,
				model: "Corolla",
				MPG: 38,
				rating: 3,
				country: "Japan",
				image: require("./assets/images/vehicles/Toyota/113.png"),
			},
			{
				vehicleModelID: 114,
				model: "Sienna",
				MPG: 35,
				rating: 4,
				country: "Japan",
				image: require("./assets/images/vehicles/Toyota/114.png"),
			},
			{
				vehicleModelID: 115,
				model: "Yaris",
				MPG: 38,
				rating: 3,
				country: "Japan",
				image: require("./assets/images/vehicles/Toyota/115.png"),
			},
		],
	},
	{
		vehicleBrandID: 12,
		brand: "Mercedes",
		logo: require("./assets/images/vehicles/Mercedes/Mercedes.png"),
		models: [
			{
				vehicleModelID: 121,
				model: "GLE350",
				MPG: 26,
				rating: 7,
				country: "Germany",
				image: require("./assets/images/vehicles/Mercedes/121.png"),
			},
			{
				vehicleModelID: 122,
				model: "GLA250",
				MPG: 26,
				rating: 7,
				country: "Germany",
				image: require("./assets/images/vehicles/Mercedes/122.png"),
			},
			{
				vehicleModelID: 123,
				model: "C300",
				MPG: 28,
				rating: 7,
				country: "Germany",
				image: require("./assets/images/vehicles/Mercedes/123.png"),
			},
			{
				vehicleModelID: 124,
				model: "E350",
				MPG: 25,
				rating: 6,
				country: "Germany",
				image: require("./assets/images/vehicles/Mercedes/124.png"),
			},
			{
				vehicleModelID: 125,
				model: "CLA250",
				MPG: 24,
				rating: 6,
				country: "Germany",
				image: require("./assets/images/vehicles/Mercedes/125.png"),
			},
		],
	},
	{
		vehicleBrandID: 13,
		brand: "Nissan",
		logo: require("./assets/images/vehicles/Nissan/Nissan.png"),
		models: [
			{
				vehicleModelID: 131,
				model: "Rogue",
				MPG: 30,
				rating: 4,
				country: "Japan",
				image: require("./assets/images/vehicles/Nissan/131.png"),
			},
			{
				vehicleModelID: 132,
				model: "Sunny",
				MPG: 36,
				rating: 2,
				country: "Japan",
				image: require("./assets/images/vehicles/Nissan/132.png"),
			},
			{
				vehicleModelID: 133,
				model: "Armada",
				MPG: 28,
				rating: 5,
				country: "Japan",
				image: require("./assets/images/vehicles/Nissan/133.png"),
			},
			{
				vehicleModelID: 134,
				model: "Sentra",
				MPG: 25,
				rating: 3,
				country: "Japan",
				image: require("./assets/images/vehicles/Nissan/134.png"),
			},
			{
				vehicleModelID: 135,
				model: "Pathfinder",
				MPG: 23,
				rating: 6,
				country: "Japan",
				image: require("./assets/images/vehicles/Nissan/135.png"),
			},
		],
	},
	{
		vehicleBrandID: 14,
		brand: "Honda",
		logo: require("./assets/images/vehicles/Honda/Honda.png"),
		models: [
			{
				vehicleModelID: 141,
				model: "Civic",
				MPG: 29,
				rating: 2,
				country: "Japan",
				image: require("./assets/images/vehicles/Honda/141.png"),
			},
		],
	},
	{
		vehicleBrandID: 15,
		brand: "Jeep",
		logo: require("./assets/images/vehicles/Jeep/Jeep.png"),
		models: [
			{
				vehicleModelID: 151,
				model: "Wrangler",
				MPG: 22,
				rating: 2,
				country: "United States",
				image: require("./assets/images/vehicles/Jeep/151.png"),
			},
		],
	},
	{
		vehicleBrandID: 16,
		brand: "BMW",
		logo: require("./assets/images/vehicles/BMW/BMW.png"),
		models: [
			{
				vehicleModelID: 161,
				model: "X",
				MPG: 29,
				rating: 2,
				country: "Germany",
				image: require("./assets/images/vehicles/BMW/161.png"),
			},
		],
	},
	{
		vehicleBrandID: 17,
		brand: "Porsche",
		logo: require("./assets/images/vehicles/Porsche/Porsche.png"),
		models: [
			{
				vehicleModelID: 171,
				model: "911",
				MPG: 20,
				rating: 2,
				country: "Germany",
				image: require("./assets/images/vehicles/Porsche/171.png"),
			},
		],
	},
	{
		vehicleBrandID: 18,
		brand: "Ford",
		logo: require("./assets/images/vehicles/Ford/Ford.png"),
		models: [
			{
				vehicleModelID: 181,
				model: "Ecosport",
				MPG: 24,
				rating: 2,
				country: "United States",
				image: require("./assets/images/vehicles/Ford/181.png"),
			},
		],
	},
	{
		vehicleBrandID: 19,
		brand: "Cadillac",
		logo: require("./assets/images/vehicles/Cadillac/Cadillac.png"),
		models: [
			{
				vehicleModelID: 191,
				model: "Escalade",
				MPG: 16,
				rating: 2,
				country: "United States",
				image: require("./assets/images/vehicles/Cadillac/191.png"),
			},
		],
	},
	{
		vehicleBrandID: 20,
		brand: "Lexus",
		logo: require("./assets/images/vehicles/Lexus/Lexus.png"),
		models: [
			{
				vehicleModelID: 201,
				model: "ES",
				MPG: 23,
				rating: 2,
				country: "United States",
				image: require("./assets/images/vehicles/Lexus/201.png"),
			},
		],
	},
];
