apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingeress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: kmalae.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
