apiVersion: apps/v1
kind: Deployment
metadata:
   name: payment-depl
spec:
   replicas: 1
   selector:
      matchLabels:
         app: payment
   template:
      metadata:
         labels:
            app: payment
      spec:
         containers:
            - name: payment
              image: kmalae/payment
              env:
                 - name: NATS_CLIENT_ID
                   valueFrom:
                      fieldRef:
                         fieldPath: metadata.name
                 - name: NATS_URL
                   value: "http://nats-srv:4222"
                 - name: NATS_CLUSTER_ID
                   value: kmalae
                 - name: MONGO_URL
                   value: "mongodb+srv://programmer:FTpt8FH8fSxVXS1e@kmalae.muye3x2.mongodb.net/?retryWrites=true&w=majority"
                 - name: JWT_KEY
                   valueFrom:
                      secretKeyRef:
                         name: jwt-secret
                         key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
   name: payment-srv
spec:
   selector:
      app: payment
   ports:
      - name: payment
        protocol: TCP
        port: 3000
        targetPort: 3000
